.PHONY: clean All

All:
	@echo "----------Building project:[ CPPStart - Debug ]----------"
	@cd "CPPStart" && "$(MAKE)" -f  "CPPStart.mk"
clean:
	@echo "----------Cleaning project:[ CPPStart - Debug ]----------"
	@cd "CPPStart" && "$(MAKE)" -f  "CPPStart.mk" clean
